strictness: high
doc-warnings: yes
test-warnings: yes
uses:
  - django
pylint:
  disable:
    - missing-docstring
    - no-self-use
    - unused-argument
pep8:
  disable:
    - N802
pep257:
  disable:
    - D100
