---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key

  - repo: git://github.com/adrienverge/yamllint
    rev: v1.11.0
    hooks:
      - id: yamllint
        args:
          - -s

  - repo: git://github.com/FalconSocial/pre-commit-python-sorter
    rev: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
      - id: python-import-sorter
        args:
          - --check-only
          - --diff

  - repo: git://github.com/guykisel/prospector-mirror
    rev: 7ff847e779347033ebbd9e3b88279e7f3a998b45
    hooks:
      - id: prospector
        additional_dependencies:
          - django
          - prospector
          - pylint<2.0.0;python_version<="2.7"
          - pylint>=2.1.1;python_version>="3.4"
          - pylint-django<2.0.0;python_version<="2.7"
          - pylint-django>=2.0.2;python_version>="3.4"

  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.4
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs

  - repo: git://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.3
    hooks:
      - id: python-bandit-vulnerability-check
        args:
          - -l
        files: .py$

  - repo: git://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
      - id: python-safety-dependencies-check
