---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key

  - repo: git://github.com/adrienverge/yamllint
    rev: v1.18.0
    hooks:
      - id: yamllint
        args:
          - -s

  - repo: git://github.com/timothycrosley/isort
    rev: 4.3.20
    hooks:
      - id: isort
        args:
          - --check-only
          - --diff

  - repo: git://github.com/PyCQA/prospector/
    rev: 1.1.7
    hooks:
      - id: prospector
        additional_dependencies:
          - django
          - ipaddress
          - prospector
          - pylint<2.0.0;python_version<="2.7"
          - pylint==2.3.1;python_version>="3.4"
          - pylint-django<2.0.0;python_version<="2.7"
          - pylint-django==2.0.10;python_version>="3.4"

  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs

  - repo: git://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args:
          - -l

  - repo: git://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
      - id: python-safety-dependencies-check

  - repo: git://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
