---
strictness: veryhigh
doc-warnings: "yes"
test-warnings: "yes"
uses:
  - django
pylint:
  disable:
    - django-not-configured
    - missing-docstring
    - no-self-use
    - unused-argument
    - useless-object-inheritance
pep8:
  disable:
    - N802
pep257:
  disable:
    - D100
    - D104
    - D203
    - D213
mccabe:
  run: false
