---
language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"
env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.2,<2.3"
install:
  - pip install $DJANGO
  - pip install coveralls
  - pip install pre-commit
script: pre-commit run --all-files && coverage run runtests.py
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "2.7"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "2.7"
      env: DJANGO="Django>=2.2,<2.3"
    - python: "3.4"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.4"
      env: DJANGO="Django>=2.2,<2.3"
after_success:
  - coveralls
