---
language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5-7.0"
  - "pypy3.6-7.3.1"
env:
  - DJANGO="Django>=2.2,<3.0"
  - DJANGO="Django>=3.0,<3.1"
install:
  - pip install $DJANGO
  - pip install coveralls
  - pip install pre-commit
script: pre-commit run --all-files && coverage run runtests.py
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=3.0,<3.1"
    - python: "pypy3.5-7.0"
      env: DJANGO="Django>=3.0,<3.1"
after_success:
  - coveralls
