---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"
install:
  - pip install $DJANGO
  - pip install coveralls
script:
  - coverage run runtests.py
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.4"
      env: DJANGO="Django>=2.0,<2.1"
after_success:
  - coveralls
