---
name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - pypy3
        django-version:
          - Django>=2.2,<3.0
          - Django>=3.0,<3.1
          - Django>=3.1,<3.2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Django
        run: pip install "${{ matrix.django-version}}"
      - name: Install coveralls
        run: pip install coveralls
      - name: Run tests
        run: coverage run ./runtests.py
      - name: Run coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: pre-commit/action@v2.0.0
